version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/nvda_url"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/nvda_zip"
    schedule:
      interval: "daily"
